<center><h1>Finding Eigenvalues</h1>
    <h2>∙ exploring factorization + iterative methods ∙</h2>
    <h3>by Rebecca Hinrichs</h3>
    <h4>Spring 2023</h4></center>

---

In [16]:
# Import libraries & dependencies
import math
import random
import numpy as np
import scipy as sp
from numpy import array
from numpy.random import rand
from numpy.linalg import cholesky, inv, norm, eig, qr
from scipy.linalg import diagsvd, svd, pinv, qr
import warnings
warnings.filterwarnings("ignore")  # suppress ill-conditioned warnings
np.set_printoptions(precision = 2)
random.seed(42)

Let $A$ be a $(5 x 3)$ randomly-generated matrix<br>
> $A = \text{np.random.randint }(0, 5, \text{size} = (5, 3))$ 

with integer elements in the interval $[0, 5)$<br>
> 1. Find the singular values of $A$, and $A^{T}$ using $SVD$.
> 2. Find the eigenvalues of $AA^{T}$ and $A^{T}A$ using $eig$, $QR$, and $SVD$.

In [2]:
# Create the matrix A
A = np.random.randint(5, size=(5,3))  # the Matrix A (4 x 3) in range [0,5)
print('\n----->> The Random Matrix A is', A.shape, '<<-----')
print(A)
print('\n----->> The Transpose Matrix A^t is', (A.T).shape, '<<-----')
print(A.T)


----->> The Random Matrix A is (5, 3) <<-----
[[3 1 0]
 [0 3 1]
 [4 0 2]
 [1 3 2]
 [4 4 3]]

----->> The Transpose Matrix A^t is (3, 5) <<-----
[[3 0 4 1 4]
 [1 3 0 3 4]
 [0 1 2 2 3]]


---
> 1. Find the singular values of $A$, and $A^{T}$ using $SVD$.

In [3]:
# Singular Value Decomposition of `A`
print('\nFinding the Singular Value Decomposition of A.....')
m, n = A.shape
print('\n<===== Let U*Sigma*V^t = A =====>')
U, sigma, VT = svd(A)
print('\nLeft Singular Vectors of A in the Matrix U is', U.shape)
print(U)
Sigma = diagsvd(sigma, m, n)  # puts vector 'sigma' into mxn matrix
print('\nThe Diagonal Singular Value Matrix SIGMA (D) is', Sigma.shape)
print(Sigma)
print('\nRight Singular Vectors of A in the Transposed Matrix V^t is', VT.shape)
print(VT)
print('\n<----- S*V*D Factorization ----->')
print(np.round(U @ Sigma @ VT))
print('\n<----- Original Matrix A ----->')
print(A)
equality = str('However NOT') if (np.count_nonzero(Sigma)!=int(Sigma.shape[0])) else str('And also')
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=', \
      f'\n {equality} linearly independent :: RANK {np.count_nonzero(Sigma)}\n')


Finding the Singular Value Decomposition of A.....

<===== Let U*Sigma*V^t = A =====>

Left Singular Vectors of A in the Matrix U is (5, 5)
[[-0.3  -0.34  0.84  0.23 -0.2 ]
 [-0.25  0.55  0.17 -0.58 -0.51]
 [-0.41 -0.64 -0.45 -0.19 -0.43]
 [-0.38  0.4  -0.25  0.74 -0.3 ]
 [-0.73  0.09 -0.02 -0.17  0.65]]

The Diagonal Singular Value Matrix SIGMA (D) is (5, 3)
[[8.75 0.   0.  ]
 [0.   4.05 0.  ]
 [0.   0.   1.44]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Right Singular Vectors of A in the Transposed Matrix V^t is (3, 3)
[[-0.67 -0.59 -0.46]
 [-0.69  0.72  0.09]
 [ 0.28  0.38 -0.88]]

<----- S*V*D Factorization ----->
[[ 3.  1.  0.]
 [-0.  3.  1.]
 [ 4.  0.  2.]
 [ 1.  3.  2.]
 [ 4.  4.  3.]]

<----- Original Matrix A ----->
[[3 1 0]
 [0 3 1]
 [4 0 2]
 [1 3 2]
 [4 4 3]]

=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+= 
 However NOT linearly independent :: RANK 3



In [4]:
# Singular Value Decomposition of `A^t`
print('\nFinding the Singular Value Decomposition of A^t.....')
m, n = (A.T).shape
print('\n<===== Let U*Sigma*V^t = A^t =====>')
U, sigma, VT = svd(A.T)
print('\nLeft Singular Vectors of A^t in the Matrix U is', U.shape)
print(U)
Sigma = diagsvd(sigma, m, n)  # puts vector 'sigma' into mxn matrix
print('\nThe Diagonal Singular Value Matrix SIGMA (D) is', Sigma.shape)
print(Sigma)
print('\nRight Singular Vectors of A^t in the Transposed Matrix V^t is', VT.shape)
print(VT)
print('\n<----- S*V*D Factorization ----->')
print(np.round(U @ Sigma @ VT))
print('\n<----- Original Matrix A^t ----->')
print(A.T)
equality = str('However NOT') if (np.count_nonzero(Sigma)!=int(Sigma.shape[0])) else str('And also')
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=', \
      f'\n {equality} linearly independent :: RANK {np.count_nonzero(Sigma)}\n')


Finding the Singular Value Decomposition of A^t.....

<===== Let U*Sigma*V^t = A^t =====>

Left Singular Vectors of A^t in the Matrix U is (3, 3)
[[ 0.67  0.69 -0.28]
 [ 0.59 -0.72 -0.38]
 [ 0.46 -0.09  0.88]]

The Diagonal Singular Value Matrix SIGMA (D) is (3, 5)
[[8.75 0.   0.   0.   0.  ]
 [0.   4.05 0.   0.   0.  ]
 [0.   0.   1.44 0.   0.  ]]

Right Singular Vectors of A^t in the Transposed Matrix V^t is (5, 5)
[[ 0.3   0.25  0.41  0.38  0.73]
 [ 0.34 -0.55  0.64 -0.4  -0.09]
 [-0.84 -0.17  0.45  0.25  0.02]
 [ 0.23 -0.58 -0.18  0.74 -0.18]
 [-0.2  -0.51 -0.43 -0.29  0.65]]

<----- S*V*D Factorization ----->
[[ 3.  0.  4.  1.  4.]
 [ 1.  3.  0.  3.  4.]
 [-0.  1.  2.  2.  3.]]

<----- Original Matrix A^t ----->
[[3 0 4 1 4]
 [1 3 0 3 4]
 [0 1 2 2 3]]

=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+= 
 And also linearly independent :: RANK 3



---
> 2a. Find the eigenvalues of $AA^{T}$ and $A^{T}A$ using $eig$.

In [5]:
# Eigenfactorization of `A At`
print('\nFinding the Eigenvalues of A*A^t using `eig`.....')
m, n = (A @ A.T).shape
print('\n<===== Eigenfactorization of A*A^t =====>')
Eig_Values, Eig_Vectors = eig(A @ A.T)
print('\n<----- Eigenvalues of A*A^t ----->')
print(np.round(Eig_Values, 2))
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Confirm Lambda = A^t*A for any Eigenvector `x`')
EigNum = n - 1            # Length of diagonal eigenvector
LambdaX = Eig_Values[EigNum] * Eig_Vectors[:, EigNum]
print('\n<----- Eigenfactorization Lambda*eig(x) ----->')
print(np.round(LambdaX, 2))
print('\n<----- Original Matrix A*A^t*eig(x) ----->')
print(np.round(A @ A.T @ Eig_Vectors[:, EigNum], 2))
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=\n')


Finding the Eigenvalues of A*A^t using `eig`.....

<===== Eigenfactorization of A*A^t =====>

<----- Eigenvalues of A*A^t ----->
[76.54 16.37  2.09  0.    0.  ]

<- - - - - - - - - - - - - - - - - - - ->

=====> Confirm Lambda = A^t*A for any Eigenvector `x`

<----- Eigenfactorization Lambda*eig(x) ----->
[-0. -0. -0.  0.  0.]

<----- Original Matrix A*A^t*eig(x) ----->
[-0.  0. -0.  0.  0.]

=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=



In [6]:
# Eigenfactorization of `At A`
print('\nFinding the Eigenvalues of A^t*A using `eig`.....')
m, n = (A.T @ A).shape
print('\n<===== Eigenfactorization of A^t*A =====>')
Eig_Values, Eig_Vectors = eig(A.T @ A)
print('\n<----- Eigenvalues of A^t*A ----->')
print(Eig_Values)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Confirm Lambda = A^t*A for any Eigenvector `x`')
EigNum = n - 1            # Length of diagonal eigenvector
LambdaX = Eig_Values[EigNum] * Eig_Vectors[:, EigNum]
print('\n<----- Eigenfactorization Lambda*eig(x) ----->')
print(np.round(LambdaX))
print('\n<----- Original Matrix A^t*A*eig(x) ----->')
print(np.round(A.T @ A @ Eig_Vectors[:, EigNum]))
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=\n')
print(f'The Eigenvalues have the same sum(AAt.cols) as sum(AtA.rows)\n')


Finding the Eigenvalues of A^t*A using `eig`.....

<===== Eigenfactorization of A^t*A =====>

<----- Eigenvalues of A^t*A ----->
[76.54 16.37  2.09]

<- - - - - - - - - - - - - - - - - - - ->

=====> Confirm Lambda = A^t*A for any Eigenvector `x`

<----- Eigenfactorization Lambda*eig(x) ----->
[-1. -1.  2.]

<----- Original Matrix A^t*A*eig(x) ----->
[-1. -1.  2.]

=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=

The Eigenvalues have the same sum(AAt.cols) as sum(AtA.rows)



---
> 2b. Find the eigenvalues of $AA^{T}$ and $A^{T}A$ using $QR$.

In [8]:
# Functions to Apply Gram-Schmidt Orthogonalization Process
def DotProduct(u,v):
    n = u.shape[0]
    product = 0.0
    for i in range(n):
        product += u[i,0]*v[i,0]
    return product
def Magnitude(w):
    magnitude = math.sqrt(DotProduct(w,w))
    return magnitude
def QRFactorization(a):
    m, n = a.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    #---begin gram-schmidt---
    for i in range(n):
        W = a[:,i:i+1]
        for j in range(i):
                W = W - DotProduct(a[:,i:i+1],Q[:,j:j+1])*Q[:,j:j+1]
        Q[:,i:i+1] = W/Magnitude(W)
    #---end gram-schmidt---
    R = Q.T @ a
    return (Q,R)
def QREigenfactorization(a):
    Q, R = QRFactorization(a)
    MaxIter = 60
    p = [1, 10, 20, MaxIter]
    E = Q.T @ a
    for i in range(MaxIter):
        EV = R @ Q @ Q.T  # because RQQ^tx=λx
        # if i+1 in p:
        #     print(f'Iteration {i+1}: \n{R}')
    return Q, R, E

In [9]:
# Eigen(QR)factorization of A A^t
print('\nFinding the QR Factorization of A*A^t.....')
print('\n<===== Set Q*R = A*A^t =====>')
Q, R, E = QREigenfactorization(A @ A.T)  # let BOTH be the square <m x m> matrix
print('\nThe Orthogonal Matrix Q is', Q.shape)
print(Q)
print('\nThe Dot Product Matrix I = Q^t*Q is', (Q.T @ Q).shape)
print(np.round(Q.T @ Q))
print('\nThe Upper Triangular Matrix R is', R.shape)
print(np.round(R))
print('\nThe Product Q^t*A*A^t agrees as', (Q.T @ A @ A.T).shape)
print(np.round(Q.T @ A @ A.T))
print('\n<----- Q*R Factorization ----->')
print(np.round(Q @ R))
print('\n<----- Original Matrix A*A^t ----->')
print(A @ A.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\nFinding the Eigenvalues of A*A^t using `QR`.....')
m, n = (A @ A.T).shape
print('\n<===== Eigenfactorization of A*A^t =====>')
print('\n<----- Eigenvalues of λ=A*A^t ----->')
print([np.round(E[vec, vec]) for vec in range(n)])
print('\n<----- Diagonal of `R` from QR ----->')
print([np.round(np.diag(R), 0)][0], '\n')


Finding the QR Factorization of A*A^t.....

<===== Set Q*R = A*A^t =====>

The Orthogonal Matrix Q is (5, 5)
[[ 0.43 -0.31 -0.79  0.69  0.69]
 [ 0.13  0.59 -0.2   0.19  0.19]
 [ 0.51 -0.49  0.52 -0.64 -0.64]
 [ 0.26  0.5   0.23 -0.28 -0.28]
 [ 0.69  0.26  0.05 -0.05 -0.05]]

The Dot Product Matrix I = Q^t*Q is (5, 5)
[[ 1.  0.  0. -0. -0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1. -1. -1.]
 [-0.  0. -1.  1.  1.]
 [-0.  0. -1.  1.  1.]]

The Upper Triangular Matrix R is (5, 5)
[[23. 17. 33. 27. 54.]
 [ 0. 13. -3. 13. 15.]
 [ 0.  0.  4.  2.  3.]
 [-3. -1. -7. -4. -8.]
 [-3. -1. -7. -4. -8.]]

The Product Q^t*A*A^t agrees as (5, 5)
[[23. 17. 33. 27. 54.]
 [ 0. 13. -3. 13. 15.]
 [ 0.  0.  4.  2.  3.]
 [-3. -1. -7. -4. -8.]
 [-3. -1. -7. -4. -8.]]

<----- Q*R Factorization ----->
[[ 6.  2.  2.  1.  5.]
 [ 2. 10. -1. 10. 12.]
 [15.  3. 29. 13. 33.]
 [ 7. 12. 12. 16. 27.]
 [16. 15. 23. 22. 42.]]

<----- Original Matrix A*A^t ----->
[[10  3 12  6 16]
 [ 3 10  2 11 15]
 [12  2 20  8 22]
 [ 6 11  8 

In [10]:
# Eigen(QR)factorization of A^t A
print('\nFinding the QR Factorization of A^t*A.....')
print('\n<===== Set Q*R = A^t*A =====>')
Q, R, E = QREigenfactorization(A.T @ A)  # let BOTH be the square <m x m> matrix
print('\nThe Orthogonal Matrix Q is', Q.shape)
print(Q)
print('\nThe Dot Product Matrix I = Q^t*Q is', (Q.T @ Q).shape)
print(np.round(Q.T @ Q))
print('\nThe Upper Triangular Matrix R is', R.shape)
print(np.round(R))
print('\nThe Product Q^t*A^t*A agrees as', (Q.T @ A.T @ A).shape)
print(np.round(Q.T @ A.T @ A))
print('\n<----- Q*R Factorization ----->')
print(np.round(Q @ R))
print('\n<----- Original Matrix A^t*A ----->')
print(A.T @ A)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\nFinding the Eigenvalues of A^t*A using `QR`.....')
m, n = (A.T @ A).shape
print('\n<===== Eigenfactorization of A^t*A =====>')
print('\n<----- Eigenvalues of λ=A^t*A ----->')
print([np.round(E[vec, vec]) for vec in range(n)])
print('\n<----- Diagonal of `R` from QR ----->')
print([np.round(np.diag(R), 0)][0], '\n')


Finding the QR Factorization of A^t*A.....

<===== Set Q*R = A^t*A =====>

The Orthogonal Matrix Q is (3, 3)
[[ 0.8  -0.53 -0.28]
 [ 0.42  0.83 -0.36]
 [ 0.42  0.17  0.89]]

The Dot Product Matrix I = Q^t*Q is (3, 3)
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

The Upper Triangular Matrix R is (3, 3)
[[52. 41. 34.]
 [ 0. 21.  9.]
 [-0. -0.  2.]]

The Product Q^t*A^t*A agrees as (3, 3)
[[52. 41. 34.]
 [ 0. 21.  9.]
 [-0. -0.  2.]]

<----- Q*R Factorization ----->
[[42. 22. 22.]
 [22. 35. 21.]
 [22. 21. 18.]]

<----- Original Matrix A^t*A ----->
[[42 22 22]
 [22 35 21]
 [22 21 18]]

<- - - - - - - - - - - - - - - - - - - ->

Finding the Eigenvalues of A^t*A using `QR`.....

<===== Eigenfactorization of A^t*A =====>

<----- Eigenvalues of λ=A^t*A ----->
[52.0, 21.0, 2.0]

<----- Diagonal of `R` from QR ----->
[52. 21.  2.] 



---
> 2c. Find the eigenvalues of $AA^{T}$ and $A^{T}A$ using $SVD$.

In [11]:
## Functions to Apply Singular Value Decomposition
def DotProduct(u,v):
    n = u.shape[0]
    product = 0.0
    for i in range(n):
        product += u[i,0]*v[i,0]
    return product
def Magnitude(w):
    magnitude = math.sqrt(DotProduct(w,w))
    return magnitude
def SVDFactorization(a):
    m, n = a.shape
    U, sigma, VT = svd(a)
    Sigma = diagsvd(sigma, m, n)
    return U, Sigma, VT.T
def SVDEigenfactorization(s):
    d = np.diag(s)
    n = len(d)
    E = np.zeros(n)
    for i in range(n):
        E[i] = np.sqrt(d[i])
    return E

In [12]:
# Eigen(SVD)factorization of A A^t
print('\nFinding the Singular Value Decomposition of A*A^t.....')
print('\n<===== Let U*Sigma*V^t = A*A^t =====>')
print('\n<--- A*A^t → (U*Sigma*V^t)*(U*Sigma*V^t)^t --->')
U, S, V = SVDFactorization(A @ A.T)
print('\nLeft Singular Vectors of A*A^t in the Matrix U is', U.shape)
print(np.round(U,2))
print('\nIdentity of Outer Product U*U^t::')
print(np.round(U @ U.T,2))
print('\nRight Singular Vectors of A*A^t in the Matrix V is', V.shape)
print(np.round(V,2))
print('\nIdentity of Inner Product V^t*V::')
print(np.round(V.T @ V,2))
print('\nThe Singular Value Matrix SIGMA is', S.shape)
print(np.round(S,2))
print('\n<----- S*V*D Factorization ----->')
print(np.round(U @ S @ V.T))
print('\n<----- Original Matrix A*A^t ----->')
print(A @ A.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\nFinding the Eigenvalues of A*A^t using `SVD`.....')
EigS = SVDEigenfactorization(S)
print('\n<===== Eigenfactorization of A*A^t =====>')
print('\n<----- Eigenvalues of λ=A*A^t ----->')
print(np.round(EigS, 2))
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=', \
      f'\n However NOT linearly independent :: RANK 3\n')


Finding the Singular Value Decomposition of A*A^t.....

<===== Let U*Sigma*V^t = A*A^t =====>

<--- A*A^t → (U*Sigma*V^t)*(U*Sigma*V^t)^t --->

Left Singular Vectors of A*A^t in the Matrix U is (5, 5)
[[-0.3   0.34  0.84  0.06 -0.3 ]
 [-0.25 -0.55  0.17  0.73  0.26]
 [-0.41  0.64 -0.45  0.47 -0.05]
 [-0.38 -0.4  -0.25 -0.1  -0.79]
 [-0.73 -0.09 -0.02 -0.49  0.47]]

Identity of Outer Product U*U^t::
[[ 1.  0. -0. -0. -0.]
 [ 0.  1. -0.  0.  0.]
 [-0. -0.  1.  0. -0.]
 [-0.  0.  0.  1. -0.]
 [-0.  0. -0. -0.  1.]]

Right Singular Vectors of A*A^t in the Matrix V is (5, 5)
[[-0.3   0.34  0.84  0.11  0.29]
 [-0.25 -0.55  0.17 -0.76  0.16]
 [-0.41  0.64 -0.45 -0.37  0.29]
 [-0.38 -0.4  -0.25  0.5   0.62]
 [-0.73 -0.09 -0.02  0.17 -0.66]]

Identity of Inner Product V^t*V::
[[ 1.  0. -0.  0. -0.]
 [ 0.  1. -0.  0. -0.]
 [-0. -0.  1.  0.  0.]
 [ 0.  0.  0.  1. -0.]
 [-0. -0.  0. -0.  1.]]

The Singular Value Matrix SIGMA is (5, 5)
[[76.54  0.    0.    0.    0.  ]
 [ 0.   16.37  0.    0.    0.

In [13]:
# Eigen(SVD)factorization of A^t A
print('\nFinding the Singular Value Decomposition of A^t*A.....')
print('\n<===== Let U*Sigma*V^t = A^t*A =====>')
print('\n<--- A^t*A → (U*Sigma*V^t)^t*(U*Sigma*V^t) --->')
U, S, V = SVDFactorization(A.T @ A)
print('\nLeft Singular Vectors of A^t*A in the Matrix U is', U.shape)
print(np.round(U,2))
print('\nIdentity of Inner Product U^t*U::')
print(np.round(U.T @ U,2))
print('\nRight Singular Vectors of A^t*A in the Matrix V is', V.shape)
print(np.round(V,2))
print('\nIdentity of Outer Product V*V^t::')
print(np.round(V @ V.T,2))
print('\nThe Singular Value Matrix SIGMA is', S.shape)
print(np.round(S,2))
print('\n<----- S*V*D Factorization ----->')
print(np.round(U @ S @ V.T))
print('\n<----- Original Matrix A^t*A ----->')
print(A.T @ A)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\nFinding the Eigenvalues of A^t*A using `SVD`.....')
EigS = SVDEigenfactorization(S)
print('\n<===== Eigenfactorization of A^t*A =====>')
print('\n<----- Eigenvalues of λ=A^t*A ----->')
print(np.round(EigS, 2))
print(f'\n=+=+=+=+=+=>> RESULTS: EQUAL! <<=+=+=+=+=+=', \
      f'\n And also linearly independent :: RANK 3\n')


Finding the Singular Value Decomposition of A^t*A.....

<===== Let U*Sigma*V^t = A^t*A =====>

<--- A^t*A → (U*Sigma*V^t)^t*(U*Sigma*V^t) --->

Left Singular Vectors of A^t*A in the Matrix U is (3, 3)
[[-0.67  0.69 -0.28]
 [-0.59 -0.72 -0.38]
 [-0.46 -0.09  0.88]]

Identity of Inner Product U^t*U::
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Right Singular Vectors of A^t*A in the Matrix V is (3, 3)
[[-0.67  0.69 -0.28]
 [-0.59 -0.72 -0.38]
 [-0.46 -0.09  0.88]]

Identity of Outer Product V*V^t::
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]

The Singular Value Matrix SIGMA is (3, 3)
[[76.54  0.    0.  ]
 [ 0.   16.37  0.  ]
 [ 0.    0.    2.09]]

<----- S*V*D Factorization ----->
[[42. 22. 22.]
 [22. 35. 21.]
 [22. 21. 18.]]

<----- Original Matrix A^t*A ----->
[[42 22 22]
 [22 35 21]
 [22 21 18]]

<- - - - - - - - - - - - - - - - - - - ->

Finding the Eigenvalues of A^t*A using `SVD`.....

<===== Eigenfactorization of A^t*A =====>

<----- Eigenvalues of λ=A^t*A ----->
[8.75 4.05 1.44]

=+=

--- 
--- 
<center><h2>Analysis</h2></center>
In this homework assignment, we used various decomposition methods to demonstrate that any matrix regardless of its shape and of its symmetry can be decomposed iteratively using the QR Factorization method, or directly using the Singular Value Decomposition method. Both allow us to extract the eigenvalues responsible for for the core (kernel) behavior of any transformational matrix A by multiplying the orthonormal matrices $A$ and $A^{T}$ via the Gram-Schmidt Process we learned about earlier. Utilizing the direct simplicity of SVD, we can simply find the eigenvalues as square roots of the singular values: a vector of scalars (i.e. length of the vectors V when multiplied by $A$) which are orthogonal to $A$'s unit vectors U. Similarly, we can find the rank of the transformation matrix $A$ by simply counting the nonzero singular values.